# Generated by Django 5.0 on 2023-12-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(default='', max_length=250)),
                ('questionType', models.CharField(choices=[('Personal information', 'Personal information'), ('Video Game Addiction Assessment', 'Video Game Addiction Assessment')], default=('Video Game Addiction Assessment', 'Video Game Addiction Assessment'), max_length=45)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaireName', models.CharField(default='', max_length=45)),
                ('dateOfTheQuestionnaire', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionText', models.CharField(default='', max_length=60)),
                ('point', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('id_Question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Options', to='Quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='id_Questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to='Quiz.questionnaire'),
        ),
        migrations.CreateModel(
            name='ResponsesQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfResponse', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True)),
                ('id_Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.patient')),
                ('id_Questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.option')),
                ('id_Reponse_Questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.responsesquestionnaire')),
            ],
        ),
    ]
