# Generated by Django 5.0 on 2023-12-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('sexe', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('dateOfBirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.user')),
                ('specialty', models.CharField(max_length=45)),
                ('scheduledTherapySessions', models.IntegerField()),
                ('cv', models.FileField(null=True, upload_to='assets/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.user')),
                ('levelOfAddiction', models.DecimalField(decimal_places=2, max_digits=4)),
                ('averageHoursOfGammingPerWeek', models.DecimalField(decimal_places=2, max_digits=5)),
                ('averageHoursOfGammingPerMounth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insomniaScore', models.DecimalField(decimal_places=2, max_digits=4)),
                ('excessiveSleepinessScore', models.DecimalField(decimal_places=2, max_digits=4)),
                ('anxietyScore', models.DecimalField(decimal_places=2, max_digits=4)),
                ('depressionScore', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[], max_length=45)),
                ('permissions', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Admin', 'Admin')], max_length=45)),
                ('idUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
