export const Data_Doctors = [
    {
      id: 1,
      username: 'mensour',
      email: 'mensourMath@gmail.com',
      photo: 'url1',
      rating: 4.4,
      phone: '(+213) 665001345',
      nbr_patients: 33,
    },
    {
      id: 2,
      username: 'john_doe',
      email: 'john.doe@example.com',
      photo: 'url2',
      rating: 2.8,
      phone: '(+1) 555-1234',
      nbr_patients: 45,
    },
    {
      id: 3,
      username: 'alice_smith',
      email: 'alice.smith@example.com',
      photo: 'url3',
      rating: 3.2,
      phone: '(+44) 20 1234 5678',
      nbr_patients: 28,
    },
    {
      id: 4,
      username: 'dr_jane_doe',
      email: 'jane.doe@example.com',
      photo: 'url4',
      rating: 5,
      phone: '(+1) 555-5678',
      nbr_patients: 52,
    },
    {
      id: 5,
      username: 'samuel_brown',
      email: 'samuel.brown@example.com',
      photo: 'url5',
      rating: 3.9,
      phone: '(+49) 30 1234 5678',
      nbr_patients: 22,
    },
    {
      id: 6,
      username: 'lisa_jones',
      email: 'lisa.jones@example.com',
      photo: 'url6',
      rating: 1.5,
      phone: '(+61) 2 1234 5678',
      nbr_patients: 37,
    },
    {
      id: 7,
      username: 'michael_white',
      email: 'michael.white@example.com',
      photo: 'url7',
      rating: 4.1,
      phone: '(+1) 555-9876',
      nbr_patients: 29,
    },
    {
      id: 8,
      username: 'emily_black',
      email: 'emily.black@example.com',
      photo: 'url8',
      rating: 3.9,
      phone: '(+44) 20 9876 5432',
      nbr_patients: 48,
    },
];
